Support copy file name
jesseduffield/lazygit pull request #1008
Opened 2020-09-19 11:03 UTC by Yuuki77

Fix #998

You can copy the file nae by clicking `ctrl+o` in inside of a commit or inside the files panel.
This is my first pr to this repo 
If you have any comments, please let me know 😄

2020-09-20 03:39 UTC, jesseduffield commented on pkg/i18n/english.go
> +			Other: "Copy the file name to the clipboard",
```suggestion
			Other: "copy the file name to the clipboard",
```
descriptions for keybindings are conventionally in lower-case :)

2020-09-20 03:40 UTC, jesseduffield requested changes
Thanks for making this PR! Just one comment about casing of the keybinding descriptions

2020-09-20 06:08 UTC, Yuuki77 commented
@jesseduffield Thank you for the review! I just updated it 😄

2020-09-20 23:25 UTC, jesseduffield commented on pkg/i18n/english.go
> +			Other: "Copy the committed file name to the clipboard",
we'll also want to downcase this

2020-09-20 23:25 UTC, jesseduffield commented on pkg/i18n/dutch.go
> +			Other: "Kopieer de bestandsnaam naar het klembord",
we'll also want to downcase this

2020-09-20 23:25 UTC, jesseduffield commented on pkg/i18n/dutch.go
> +			Other: "Kopieer de vastgelegde bestandsnaam naar het klembord",
we'll also want to downcase this

2020-09-20 23:25 UTC, jesseduffield requested changes
couple more things :)

2020-09-21 05:28 UTC, Yuuki77 commented
@jesseduffield Sorry I missed them.
It should be good now 💪

2020-09-21 05:35 UTC, jesseduffield commented
Tested and it works! thanks heaps for making this, I'll be using it myself :)

2020-09-21 05:35 UTC, merged