Allow creation of annotated tags
jesseduffield/lazygit pull request #1469
Opened 2021-09-11 23:38 UTC by fsmiamoto

## What
Allow the creation of annotated tags.
This implementation only supports adding a message to the tag but it could be extended in the future.

## Why
This was requested in #1381 as currently we only support creating the so called *lightweight tags*

## TODOs
- Add tests
- Review translation messages

2021-09-11 23:55 UTC, fsmiamoto commented
@jesseduffield This PR still has some rough edges but let me know what you think of the general approach :)

2021-09-12 03:29 UTC, jesseduffield requested changes
nice work! Couple small things

2021-09-12 03:29 UTC, jesseduffield commented on pkg/gui/commits_panel.go
> +	return gui.createMenu(gui.Tr.TagMenuTitle, items, createMenuOptions{showCancel: false})
I would go `showCancel: true` just because it's harmless to do so

2021-09-12 03:29 UTC, jesseduffield commented on pkg/i18n/english.go
> +		TagMenuTitle:                        "create tag",
menu titles should use 'Sentence case' so this should be 'Create tag'

2021-09-12 03:29 UTC, jesseduffield commented on pkg/i18n/english.go
> +		LightweightTag:                      "lightweight tag",
conventionally we prefix lowercase fields with 'Lc' (see line 902 below)

2021-09-12 20:32 UTC, fsmiamoto commented
Took the opportunity to give some updates to the docs on Integration Tests as the commands there were not working as expected.

Not sure if what I did to fix the tests is the right thing but here's what I've done:
- Run the Integration Test TUI with `go run ./test/lazyintegration/main.go`
- Re-record the tests related to tags, trying/guessing what was done at those tests - not sure if there's a good way to visualize the actions that were there before.

Although these tests are slow by their own nature, I've really liked the general approach! 
Some things are not quite there in the Integration Test TUI - the test list didn't scroll properly for me - so I might give some help there afterwards.

2021-09-12 20:33 UTC, fsmiamoto commented
Also, not sure why the linting is failing on me :sweat_smile: 
Maybe a different `gofmt`version on the CI? I'm not able to reproduce it locally.

2021-09-19 13:08 UTC, fsmiamoto commented
Linting problems were caused by Go 1.17, fixed at #1479.

2021-12-25 21:11 UTC, fsmiamoto commented
Fixed the `pushTag` by adding an extra `Enter` input. Should be good to go now :)

2021-12-26 06:08 UTC, jesseduffield commented
Just tested and it works fine. Nice work!

2021-12-26 06:08 UTC, merged