Pull request support for Azure DevOps (dev.azure.com)
jesseduffield/lazygit pull request #1567
Opened 2021-11-05 20:13 UTC by tiwood

This adds support Pull request support for `Azure DevOps` remotes.

Closes #1548

Thanks @jesseduffield for this great tool, I'm using it daily 🥳️

2021-11-19 12:23 UTC, MiroslavMikus commented
Thanks @tiwood. Works like a charm! :grin:

## Apporoved :+1:

2021-12-25 11:39 UTC, jesseduffield requested changes
Nice work :) Coincidentally @TheBlob42 is working in the same code, and both of your PRs are adding service-specific code to the getRepoInfoFromURL function. Here's the comment I left on the other PR suggesting a change to how we do this so that we're ensuring that service-specific logic lives on the service itself: https://github.com/jesseduffield/lazygit/pull/1604#discussion_r775129451

I will leave it up to the two of you to decide who wants to implement the suggestion :) Let me know if you need any clarification

2021-12-26 05:50 UTC, jesseduffield commented
Given a few people were working in the same part of the codebase I've gone ahead and implemented the regex approach myself: https://github.com/jesseduffield/lazygit/pull/1637

Let me know if you have any questions around how to add azure as a service given the new code structure

2021-12-30 12:14 UTC, ecosse3 commented
Thank you for your contribution. I'm waiting for this PR. In meanwhile I share my workaround to create PRs to Azure DevOps from lazygit. It requires configuring Azure DevOps CLI before ([docs](https://docs.microsoft.com/en-us/azure/devops/cli/?view=azure-devops)).

That's my custom menu to create PR from selected local branch.

```yml
  - key: 'A'
    description: 'Create pull request to Azure Devops'
    prompts:
      - type: 'input'
        title: 'Title'
        initialValue: "#{{ .SelectedLocalBranch.Name }}"
      - type: 'input'
        title: 'Description'
      - type: 'menu'
        title: 'Draft Mode'
        options:
          - name: 'no'
            value: 'false'
          - name: 'yes'
            value: 'true'
      - type: 'input'
        title: 'Reviewers'
        initialValue: ""
      - type: 'input'
        title: 'Target Branch'
        initialValue: "dev"
    context: 'localBranches'
    command: 'az repos pr create --delete-source-branch true --title "{{index .PromptResponses 0}}" --description "{{index .PromptResponses 1}}" --draft {{index .PromptResponses 2}} --detect true --reviewers "{{index .PromptResponses 3}}" -s "{{ .SelectedLocalBranch.Name }}" -t "{{index .PromptResponses 4}}" --work-items "{{ .SelectedLocalBranch.Name }}" --open'
    loadingText: 'Creating Pull Request...'
```

Target Branch could be of course list of all available remote branches by customizing **menuFromCommand**.

One thing I just can't do is use `sed` command on Go Templates like _{{ .SelectedLocalBranch.Name }}_. If the branch name is for example _bug/33333_ I would like to take just number.

2021-12-30 15:11 UTC, tiwood commented
@jesseduffield, I really like the new approach.
I've updated the code accordingly.

Right now I parse the Azure DevOps organization and the project together as `owner`, which currently works fine, but may require changes in the future if new features are added or the URL scheme changes.

Example:

```
URL: git@ssh.dev.azure.com:v3/my-organization/my-project/my-repo
Owner: my-organization/my-project
Repo: my-repo
```

2022-01-10 21:22 UTC, tiwood commented
 @jesseduffield, this is ready for another review.

2022-01-11 07:10 UTC, MiroslavMikus commented
Hey @tiwood, the latest version does not work anymore -_-
<img width="560" alt="image" src="https://user-images.githubusercontent.com/29312172/148896431-701a48fd-73af-404e-b816-1a0ebaf7496b.png">

Seems to be issue with the URL:
https://dev.azure.com/company/project/_git//_git/repo/pullrequestcreate?sourceRef=sourceBranch

Manually changing to:
https://dev.azure.com/company/project/_git/repo/pullrequestcreate?sourceRef=sourceBranch
does fix the issue.

Tested with commit e849aed4
<img width="378" alt="image" src="https://user-images.githubusercontent.com/29312172/148896902-0e9593c0-5965-4dbe-bfed-491457b08351.png">

2022-01-12 12:00 UTC, jesseduffield commented
@tiwood I've pushed a refactor commit so that we don't need have conditional logic based on the service definition. I've also made it so that you can use org/project/repo in the url regex. Would you be able to add a spec or two to `pkg/commands/hosting_service/hosting_service_test.go` to verify that everything works?

2022-01-12 12:04 UTC, jesseduffield commented on pkg/commands/hosting_service/hosting_service_test.go
> -func TestGetRepoInfoFromURL(t *testing.T) {
shame on me for testing a private function which then got refactored out of existence

2022-01-18 12:50 UTC, tiwood commented
@jesseduffield, I've added the tests and fixed the regex for HTTP remote URLs

2022-02-18 14:30 UTC, tiwood commented
@jesseduffield, any chance we can pick this up again?

2022-03-16 09:52 UTC, merged

2022-03-16 09:54 UTC, jesseduffield commented
@tiwood apologies for the late response, but we made it! Nice work :)

I pushed a couple commits myself to fix things up. Of note is that I've stuck to the semi-recent change to this method:
```go
func (self *HostingServiceMgr) getServiceDomain(repoURL string) (*ServiceDomain, error) {
	candidateServiceDomains := self.getCandidateServiceDomains()

	for _, serviceDomain := range candidateServiceDomains {
		if strings.Contains(repoURL, serviceDomain.gitDomain) {
			return &serviceDomain, nil
		}
	}

	return nil, errors.New(self.tr.UnsupportedGitService)
}
```

This PR had us also checking on the service provider but I assume that's just based on what was previously there on master. If I've made an error here let me know