WIP: 1489: added demonstration for using an Editor implementation for menu…
jesseduffield/lazygit pull request #1583
Opened 2021-11-17 20:18 UTC by i78

**WORK IN PROGRESS**

Pull-Request for enabling filtering in menus.

Open issues:
- A keypress on ESC is not caught properly and forwarded to the editor. So, the first keypress on ESC just resets the search highlighting, the second closes the menu. If there would be a way to catch the keypress, it would be fine.
- I am not aware of any event thrown when a submenu is opened, so the state of the filter is not cleaned up properly when i.E. one filters the "x" menu by "filter" and opens the "Filter" submenu.

2021-11-17 21:16 UTC, jesseduffield commented
Looking good! Some feedback:
* we should introduce another view that the user can toggle to in order to type in their needle. This has two benefits: firstly, it allows us to reserve other keybindings, e.g. for traversing the list (j and k currently go up and down the list). We should show that view underneath the menu view and allow the user to press tab to switch focus back and forth between the views, similar to how we currently do with checking out a branch by name (pressing 'c' in the branches panel).
* we should use `utils.FuzzySearch` for filtering so that we're forgiving about typos. This will mean that some menu items will not appear with highlighted text due to the lack of an exact match but I'm okay with that

As for catching the ESC key, we have some keybindings that are built into the view when we're in search mode and ESC is one such keybinding. This makes sense when you're specifically searching for an item through the typical search flow using the '/' key, but in this context it's less appropriate. It sounds like we need to add some code in the gocui's View struct that lets us distinguish between the two use cases. To be honest though I think that to keep things simple we should scrap the search stuff in this PR and handle that in a follow-up PR given that it's only a nice-to-have.

As for opening a sub-menu, we shouldn't need to check for a menu close event. It should suffice to instead just clear the filter whenever we open a new menu.

2021-11-26 14:17 UTC, i78 commented
I like that, I will add a new commit to the PR resembling the approach you described.

2021-12-25 11:35 UTC, jesseduffield requested changes
marking as changes requested for my own bookkeeping :)

2023-05-01 10:49 UTC, jesseduffield commented
@i78 I'm closing this as stale. Feel free to re-open if you make more changes

2023-05-01 10:49 UTC, closed without merging