Opening files with filenumber 1730
jesseduffield/lazygit pull request #1751
Opened 2022-01-31 21:54 UTC by StefanMich

2022-02-01 08:15 UTC, jesseduffield commented on pkg/commands/oscommands/os_test_default.go
> -		s.test(oSCmd.OpenFile(s.filename))
can we add a test verifying that if we've configured OpenCommandTemplate that the file number does indeed come through as expected?

2022-02-01 08:15 UTC, jesseduffield commented on pkg/config/user_config.go
> +	// OpenCommandTemplate is the command template for editing a file
```suggestion
	// OpenCommandTemplate is the command template for opening a file
```

2022-02-01 08:15 UTC, jesseduffield requested changes
couple things :)

2022-02-09 20:29 UTC, StefanMich commented
Fixed the typo and added a test.
I had to rename the test to be included in the test run - This seems to be and issue with other test files as well

I had to change the setup in the tests to comply with the new format (OpenCommand and OpenCommandTemplate). This made me realize that any users having set the OpenCommand like in the tests in their config will have the opencommand broken (It will insert {{filename}} into the template, which will then not be resolved). I don't see any backwards compatible way to do this though

2022-03-16 08:55 UTC, jesseduffield commented
I think the best approach is to actually continue using OpenCommand. On master the OpenCommand field already has a {{filename}} in it. I think we should just stick with that and now allow for {{line}} to be used as well. This means we're a bit out of sync with the EditCommand stuff but it really does make sense to only have a single field per open/edit. What do you think?

2022-03-18 13:39 UTC, StefanMich commented
Had a similar thought, it feels superfluous with two, and migration would just be annoying for users. This will simply things a bit. Thanks, I'll take a look at it

2022-03-21 22:16 UTC, StefanMich commented
Seems that PR #1804 fixed this by using editcommand directly, which seems perfectly reasonable

2022-03-21 22:16 UTC, closed without merging