Record current directory on switch instead of exit
jesseduffield/lazygit pull request #1814
Opened 2022-03-15 13:16 UTC by davdroman

Implements #1800

2022-03-16 10:08 UTC, jesseduffield commented
Nice one :)

The shift+Q thing is problematic: I do believe some users are making use of that feature (I myself was for a while but haven't found myself using it lately). We can retain that functionality by saving the current directory open first opening the app and if you hit shift+Q to quit then we'll write that back to the file before quitting.

Only tricky thing is to decide is when to capture it and where to store it. We'll want to capture it as soon as possible i.e. before we switch directories. I believe we first call os.Chdir in `pkg/app/app.go` so we'll need to capture the value before then, and then it's a matter of where to put it.

I think we should pass it to the Gui struct so that that struct has it on hand to write it back before quitting when shift+Q is pressed.

I'm aware this is some unfortunate feature creep for your first PR haha but I think it should still be fairly straightforward (if a little hairy). Lemme know your thoughts :)

2022-03-16 10:14 UTC, davdroman commented
@jesseduffield that sounds like a sensible approach. It feels like a slightly more challenging implementation but I can give it a shot and report back if I get lost somewhere.

2022-03-16 10:29 UTC, jesseduffield commented
Awesome, sounds good

2022-03-16 11:44 UTC, davdroman commented
@jesseduffield alright here we go! Now the old functionality is retained along with the new 👍

2022-03-16 23:19 UTC, jesseduffield requested changes
Awesome work, just one comment

2022-03-16 23:19 UTC, jesseduffield commented on pkg/gui/gui.go
> +	InitialRepoDir string
could we rename this to just `InitialDir`, just because it's not necessarily going to be the root directory of the repo

2022-03-17 07:43 UTC, jesseduffield commented
@davdroman I've taken the liberty of updating that field name so that we can get this PR merged :) Reason being that I'm about to merge in the mother of all refactor PRs and I'd hate to yet again force you to update the code

2022-03-17 07:46 UTC, davdroman commented
@jesseduffield thank you! I was going to do it this morning but haven't arrived to the office yet. By all means feel free to merge :)

2022-03-17 08:01 UTC, merged