Add git difftool support (keybinding <c-t>)
jesseduffield/lazygit pull request #1846
Opened 2022-03-27 20:46 UTC by zeevro

I've added the ability to launch `git difftool` for what's currently in the diff screen.

2022-03-30 11:07 UTC, Ryooooooga commented on pkg/gui/diffing.go
> +	file := gui.currentlySelectedFilename()
```suggestion
	file := gui.currentlySelectedFilename()
	if file == "" {
		file = gui.getSelectedPath()
	}

```

for Staged/Unstaged Changes panel

2022-03-30 11:08 UTC, Ryooooooga commented on pkg/gui/diffing.go
> +		cmdStr += " -- " + file
```suggestion
		cmdStr += " -- " + gui.os.Quote(file)
```

2022-07-06 07:22 UTC, mark2185 commented on pkg/i18n/english.go
> +		LcLaunchDiffTool:                    "Launch git difftool",
`Lc` in `LcSomeTitle` actually denotes `lowercase`, could you change it to `launch git difftool` then?

2022-08-12 02:16 UTC, barreiroleo commented
Hello there! Any updates with this PR?

2022-09-24 06:18 UTC, jesseduffield requested changes
Marking as changes requested for my own bookkeeping. Let me know if you need any guidance with this @zeevro

2024-01-10 02:00 UTC, jesseduffield commented
This is superceded by https://github.com/jesseduffield/lazygit/pull/3156. Closing

2024-01-10 02:00 UTC, closed without merging