Add command to reset the commit author from the commits panel.
jesseduffield/lazygit pull request #1893
Opened 2022-04-22 14:29 UTC by JensPfeifle

First of all I want to say thanks for the great tool!

This adds a command for resetting the author of a single commit, as described in #1871. I haven't been able to run the test suite yet (doesn't seem to play nice with the docker image?), but am happy to spend some more time to add some tests if required. 

One thing I'm no so not sure about is the default keybinding, to `a`. Any good alternatives?

There's also a version which allows the user to edit the author name in [this branch](https://github.com/JensPfeifle/lazygit/tree/change_author_name), but this is simpler and should cover the general use-case.

2022-05-02 07:08 UTC, mark2185 commented on pkg/commands/git_commands/commit.go
> +// Reset the author of the topmost commit.
The convention is to start the comment with the name of the element it describes, in this case that would be `ResetAuthor reset the author of the topmost commit`

2022-05-06 09:44 UTC, jesseduffield requested changes
Awesome work, left some feedback

2022-05-06 09:44 UTC, jesseduffield commented on pkg/config/user_config.go
> +				ResetCommitAuthor:              "a",
I can't think of any better option than this keybinding. Although 'a' typically means 'select everything in this panel', it doesn't make any sense to select all commits. And I see the value in having 'A' and 'a' both relating to amending, with the former being for amending file changes, and the latter being for amending metadata like the author.

For what it's worth in future I want this keybinding to open a menu with an additional option to edit the author explicitly, but we don't need to do that in this PR.

2022-05-06 09:47 UTC, jesseduffield commented
@JensPfeifle as for the test suite, do you mean like running `go test ./...` or are you talking about the integration tests. The guide for integration tests is [here](https://github.com/jesseduffield/lazygit/blob/master/docs/Integration_Tests.md). I think this would be a good case for an integration test where we start with a commit and then open up lazygit and amend the author to the current author, but don't stress if you can't get it working on your end.

2022-05-07 14:39 UTC, JensPfeifle commented on pkg/i18n/english.go
> +		SureResetCommitAuthor:               "Are you sure you want to reset the author of this commit?",
Good point - how about "The author field of this commit will be updated to match the configured user. This also renews the author timestamp. Continue?"

2022-05-07 14:46 UTC, JensPfeifle commented
Thanks for the feedback!
I was having trouble with the integration tests, but got it today and managed to record a simple test.

2022-05-08 00:46 UTC, jesseduffield commented on pkg/i18n/english.go
> +		SureResetCommitAuthor:               "Are you sure you want to reset the author of this commit?",
Yep that's perfect

2022-05-08 00:50 UTC, jesseduffield commented
Great work on the integration test. Heads up, I've pushed a commit that changes how we generate the snapshot of the resultant repo to include the author name and email in the git log result. Previously we had the chance of a false positive because we weren't checking against that.

2022-05-08 03:33 UTC, jesseduffield commented
Looks like we needed to rebase onto master to get that cheatsheet thing working (now that the Japanese language has been added). I'm pushing some commits on your behalf to get this merged because the next step (allowing an author to be set) should be fairly straightforward and I'm gonna make a contributor PR guide from it.

2022-05-08 03:39 UTC, merged

2022-05-08 03:39 UTC, jesseduffield commented
Merged. Great work @JensPfeifle

2022-05-08 13:28 UTC, JensPfeifle commented
Great, thanks!