added gitVersion to version flag
jesseduffield/lazygit pull request #2265
Opened 2022-11-12 10:32 UTC by nitinmewar

Signed-off-by: nitin mewar <nitinmewar28@gmail.com>

added gitVersion to version flag.

2022-11-12 20:43 UTC, nitinmewar commented
@jesseduffield please review this.

2022-11-13 01:55 UTC, jesseduffield commented
Looks good to me. Just running tests now

2022-11-13 01:59 UTC, jesseduffield requested changes
linting issue

2022-11-13 01:59 UTC, jesseduffield commented on pkg/app/entry_point.go
> +func getGitVersionInfo() string {
We need a blank line between this function and the previous one

2022-11-13 23:00 UTC, merged

2022-11-13 23:01 UTC, jesseduffield commented
nice work @nitinmewar

2022-11-14 13:40 UTC, nitinmewar commented
@jesseduffield thank you.