Commit in staged/unstaged menu
jesseduffield/lazygit pull request #2298
Opened 2022-11-27 00:15 UTC by arnaudperalta

- **PR Description**
3 new commit actions in staged/unstaged menu.
Closes https://github.com/jesseduffield/lazygit/issues/2285

- **Please check if the PR fulfills these requirements**

* [ ] Cheatsheets are up-to-date (run `go run scripts/cheatsheet/main.go generate`)
* [ ] Code has been formatted (see [here](https://github.com/jesseduffield/lazygit/blob/master/CONTRIBUTING.md#code-formatting))
* [ ] Tests have been added/updated (see [here](https://github.com/jesseduffield/lazygit/blob/master/pkg/integration/README.md) for the integration test guide)
* [ ] Text is internationalised (see [here](https://github.com/jesseduffield/lazygit/blob/master/CONTRIBUTING.md#internationalisation))
* [ ] Docs (specifically `docs/Config.md`) have been updated if necessary
* [ ] You've read through your own file changes for silly mistakes etc

2022-11-27 00:16 UTC, arnaudperalta commented
Does this PR needs new integration tests ?

2022-11-27 13:57 UTC, mark2185 commented
> Does this PR needs new integration tests ?

Well, it would be nice :)

Just so we know for sure that everything works as expected, and this seems testable. At least for the non-"open-up-external-editor" cases.

2022-11-27 16:36 UTC, arnaudperalta commented
> > Does this PR needs new integration tests ?
> 
> Well, it would be nice :)
> 
> Just so we know for sure that everything works as expected, and this seems testable. At least for the non-"open-up-external-editor" cases.

I just wrote two integration tests, one who commits in the staged files menu and the other who commits in the unstaged one. Should I add two more with commit without pre-hook ?

2022-11-27 16:44 UTC, mark2185 requested changes
Just a few things :)

2022-11-27 16:44 UTC, mark2185 commented on pkg/integration/tests/commit/staged.go
> +		shell.CreateFile("myfile2", "myfile2 content")
You can chain these, e.g.
```
	shell.
             CreateFile("myfile", "myfile content").
	     CreateFile("myfile2", "myfile2 content")
```

Just to be consistent with other tests.

2022-11-27 16:44 UTC, mark2185 commented on pkg/integration/tests/commit/staged.go
> +		assert.MatchHeadCommitMessage(Equals(commitMessage))
We should also assert that we're still in the `Staged panel` after it's done.

2022-11-27 16:44 UTC, mark2185 commented on pkg/integration/tests/commit/unstaged.go
> +		assert.MatchHeadCommitMessage(Equals(commitMessage))
We should also assert that we're still in the `Unstaged panel` after it's done.

2022-11-27 17:00 UTC, mark2185 commented
> Should I add two more with commit without pre-hook ?

I'd rather actually that we rework the whole "run commit without hooks" with the whole `WIP` prefix because that seems rather hacky, so I'm not sure if we should write tests for it just yet. Summoning @jesseduffield .

Also, I'd like a test that stages a single line, commits it, then stages another, and commits that because that's a real use case. The current tests do look like they're doing what one would expect, but it's even nicer if the tests look like something a real user would do :)

2022-11-27 22:44 UTC, jesseduffield commented
The run commit without hooks thing is a little hacky but I think it's still worth having a test for it because the hackiness that we would want to fix shouldn't break the test. That is: currently when we press 'W' the commit message panel comes up and if you hit enter on that, so long as the 'WIP' prefix is still there in the text area it'll commit without invoking hooks. What I want to change is to make it so that when you press 'w' it will skip hooks no matter what content you write (but I'd still have the 'WIP' prefix there to start with). So I think a test is warranted.

2022-11-28 19:36 UTC, arnaudperalta commented
I wrote two new tests with the pre-commit hook commit feature.
Tell me if I need to add a proper hook for these tests.

2022-11-30 21:01 UTC, arnaudperalta commented
Any feedbacks @mark2185 @jesseduffield ? And is this normal that the CI is sometimes failing ?

2022-11-30 22:12 UTC, jesseduffield commented
code all looks good @arnaudperalta . I suspect the failing integration test is a legit failure. I've just done a rebase onto master so we'll see if it fails again

2022-11-30 22:31 UTC, arnaudperalta commented
> code all looks good @arnaudperalta . I suspect the failing integration test is a legit failure. I've just done a rebase onto master so we'll see if it fails again

Thanks, seems good now.

2022-11-30 23:01 UTC, merged

2022-11-30 23:02 UTC, jesseduffield commented
Nice one, thanks for making this @arnaudperalta !

2022-12-16 14:47 UTC, ooloth commented
Excited for this one to go out. 🙌