Clear staging after commit
jesseduffield/lazygit pull request #2377
Opened 2023-01-18 16:30 UTC by shinhs0506

- **PR Description**
fixes https://github.com/jesseduffield/lazygit/issues/2363
invoke stage panel refresh on successful commit

- **Please check if the PR fulfills these requirements**

* [x] Cheatsheets are up-to-date (run `go run scripts/cheatsheet/main.go generate`)
* [x] Code has been formatted (see [here](https://github.com/jesseduffield/lazygit/blob/master/CONTRIBUTING.md#code-formatting))
* [x] Tests have been added/updated (see [here](https://github.com/jesseduffield/lazygit/blob/master/pkg/integration/README.md) for the integration test guide)
* [ ] Text is internationalised (see [here](https://github.com/jesseduffield/lazygit/blob/master/CONTRIBUTING.md#internationalisation))
* [x] Docs (specifically `docs/Config.md`) have been updated if necessary
* [x] You've read through your own file changes for silly mistakes etc

2023-01-19 05:39 UTC, mark2185 commented
LGTM

2023-01-26 01:57 UTC, jesseduffield commented on pkg/integration/tests/commit/staged.go
> -		// TODO: assert that the staging panel has been refreshed (it currently does not get correctly refreshed)
we should add an assertion here that the staging panel has been refreshed (there are examples of asserting on a view's contents in various tests so I'd take a a look at those)

2023-01-26 01:58 UTC, jesseduffield requested changes
one thing :) (haven't functionally tested)

2023-01-29 03:02 UTC, jesseduffield commented on pkg/integration/tests/commit/staged.go
> +		t.Views().Staging().IsFocused().Tap(func() {
The Tap function is only really needed when we want to make an assertion about another view and then afterwards chain more method calls onto the original one. But in this case it's not necessary; we can instead go:
```go
t.Views().StagingSecondary().
	IsEmpty()
	
t.Views().Staging().
	IsFocused().
	Content(Contains("+myfile content")).
	Content(DoesNotContain("+with a second line"))

```

2023-01-29 03:02 UTC, jesseduffield commented on pkg/integration/tests/commit/staged_without_hooks.go
same here

2023-01-29 03:02 UTC, jesseduffield requested changes
one thing :)

2023-01-31 22:22 UTC, shinhs0506 commented
resolved :)

2023-01-31 22:42 UTC, jesseduffield commented
Sweet. Code looks good, I wanna manually test this before merging (hopefully today)

2023-02-01 10:56 UTC, jesseduffield commented
Testing this locally I notice a flicker in the main panel when we commit from either the main panel or the files panel. We wanna find a way around that before we merge this

2023-02-02 04:09 UTC, shinhs0506 commented
are you able to upload a recording of the flicker? just so that we are on the same page

2023-02-05 02:49 UTC, jesseduffield commented
In this recording I first open up the master branch (that's what lg does) and then show there's no flickering, and then on this PR's branch (that's what gg does) there is flickering:
https://user-images.githubusercontent.com/8456633/216798926-35f40573-1490-46cd-a2a2-62be536bc443.mov

2023-03-04 17:46 UTC, stefanhaller commented
Since I run into this bug quite often, and it's confusing and annoying every time, I wonder if it would be an option to merge the fix in the current state and open an issue to address the flicker problem later. What do you think @jesseduffield?

(BTW, I find the flickering barely noticeable anyway, on my machine at least.)

2023-03-13 20:40 UTC, stefanhaller commented
I debugged the flicker issue, here's what I found:

- onCommitSuccess calls Refresh(Staging) after the commit was made, but before the files panel is refreshed
- refreshStagingPanel calls handleStagingEscape because both main views have become empty
- this calls PushContext(gui.State.Contexts.Files) (but that context is already active in this case)
- this deactivates the files context, and then activates it again
- this calls RenderToMainViews
- since the files panel hasn't been refreshed yet, this calls the same diff command again, for the same file that had the staged changes before. Since the commit has just been made, this diff is now empty and the screen goes black.
- Then the files panel is refreshed, and the main view displays whatever file is selected now.

The flicker can be avoided by not deactivating and activating the context if the currently active context is pushed again. Here's a commit that does this: https://github.com/stefanhaller/lazygit/commit/3b7b171adf7f33c7b6ed0dd016e26ae

@jesseduffield Let me know what you think about this approach.

@shinhs0506 Can you try cherry-picking the above commit to your branch to see if it improves the flicker? (It does for me.)

2023-03-18 07:53 UTC, jesseduffield commented
@stefanhaller that commit looks sensible to me. But I'll need to do some testing on it: it may be that we have code that depends on the activateContext function being called on already-active contexts. That is: there may be too kinds of things happening in that function: one for 'activated the first time' and another for 'activated at any time'.

2023-03-18 07:54 UTC, jesseduffield commented
@stefanhaller one thing I notice upon testing is that the options view (at the bottom left in blue) does not appear when you initially start the program

2023-03-18 10:00 UTC, stefanhaller commented
5b10b333d843 should fix the missing options view problem on startup (if that's the right way to do it). Can you think of any other problems with this approach?

2023-03-19 00:42 UTC, jesseduffield commented
I do worry that calling `PushContext` before calling `gui.g.MainLoop()` could get us into trouble, but if the integration tests all pass I'm happy

2023-03-19 00:56 UTC, jesseduffield commented
I've done some testing and it looks good. I'm happy to push those commits to this branch. Did you want to squash them first @stefanhaller ?

2023-03-19 07:20 UTC, stefanhaller commented
Great. I'm fine with merging the branch as is, with the two commits cherry-picked to it.

2023-03-24 08:08 UTC, stefanhaller commented
@jesseduffield Is this still waiting for something, or did you just forget to merge it? 😉

2023-03-24 08:13 UTC, merged