Update icons to use Nerd Fonts v3.
jesseduffield/lazygit pull request #2604
Opened 2023-05-06 19:12 UTC by gotgenes

- **PR Description**

This updates icons to use Nerd Fonts v3 which had [breaking changes](https://www.nerdfonts.com/releases). I used all the recommendations from nerdfix check except for the Azure icon, which I changed to `nf-md-microsoft_azure`.

Fixes #2603.

- **Please check if the PR fulfills these requirements**

* [ ] Cheatsheets are up-to-date (run `go run scripts/cheatsheet/main.go generate`)
* [ ] Code has been formatted (see [here](https://github.com/jesseduffield/lazygit/blob/master/CONTRIBUTING.md#code-formatting))
* [ ] Tests have been added/updated (see [here](https://github.com/jesseduffield/lazygit/blob/master/pkg/integration/README.md) for the integration test guide)
* [ ] Text is internationalised (see [here](https://github.com/jesseduffield/lazygit/blob/master/CONTRIBUTING.md#internationalisation))
* [ ] Docs (specifically `docs/Config.md`) have been updated if necessary
* [ ] You've read through your own file changes for silly mistakes etc

2023-05-11 08:32 UTC, uloco commented
Please please merge this soon, I need this so badly :P

2023-05-11 14:30 UTC, gotgenes commented
I'm not sure your particular reasons for not upgrading Nerd Fonts, however, in general, I would recommend all users upgrade. Probably the most important breaking change for the global community is that [it fixes overwriting glyphs, which negatively impacts some of our users in Asia and other world regions](https://github.com/ryanoasis/nerd-fonts/issues/365).

If what's holding back a user from upgrading is use of v2 code points in their personal configuration files (e.g., Neovim configuration), [nerdfix](https://github.com/loichyan/nerdfix) provides tooling around the translation from Nerd Fonts v2 to v3. It can even be automated.

If what's holding a user back from upgrading is they generated their own patched font using the v2 code points, I expect the user to also be able to patch the font with v3 just as easily, if not more so.

Other projects are approaching this situation by having users either upgrade to v3 or pinning to the prior release of the tool/plugin/library prior to updating backwards incompatible code points.

I'm not in agreement that it is worth the effort to create a (potentially breaking) change in the Lazygit config just to support both Nerd Fonts v2 and v3 in the same version of Lazygit, or any software, at this point.

v3 is a net win for the global community. It's unclear there will ever be a v4 and so I don't think this is a useful as an extensible solution to a what-if scenario. At that point, there may be a new and better solution than Nerd Fonts.

2023-05-11 15:29 UTC, brneor commented
Even though I agree that updating NerdFont to v3 and updating software so support it is the "correct" way to do things, there's a caveat.

User @Finii stated in a discussion somewhere (maybe Lunarvim's repo, I couldn't find it) about the instability of Material Icons codepoint changes (something like that). In resume, there's no way to guarantee that there'll be no more breaking changes like this in the future.

I don't know if this information changes the way you're planning things, but I thought it was important to share.

2023-05-11 15:57 UTC, gotgenes commented
> User @Finii stated in a discussion somewhere (maybe Lunarvim's repo, I couldn't find it) about the instability of Material Icons codepoint changes (something like that). In resume, there's no way to guarantee that there'll be no more breaking changes like this in the future.
> 
> I don't know if this information changes the way you're planning things, but I thought it was important to share.

I would definitely be in agreement with @jesseduffield's requested approach of supporting multiple versions of Nerd Font simultaneously if I had high confidence that Nerd Fonts expected breaking changes to come more frequently than they have.

As it stands, the [last major version release was over five years ago](https://github.com/ryanoasis/nerd-fonts/releases/tag/v2.0.0). Without other substantial information, the trend looks like years-long cycles.

Has @ryanoasis published plans for Nerd Font's roadmap and anticipated stability or instability? That would be informative.

2023-05-11 16:19 UTC, Finii commented
> This PR will break icons for anybody on nerd fonts v2 (like myself).

Well, the new codepoints have already been introcudes with Nerd Fonts `v2.3.?`, so it will only break if you are still on `v2.2.x`. Usually people are on `v2.3.3`. Well, except one person just wrote he/she uses `v2.2`; for them a switch would be indeed needed.

Sorry for the breaking change, but that has been simmering for several years now, and we have to set this right at some point.

> the instability of Material Icons codepoint changes

That is correct, they do not claim codepoint stability, but if you have a look at the past releases (after they adopted the `F0000` range) the codepoints **do look** stable. They just do not write it down as goal.

![image](https://github.com/jesseduffield/lazygit/assets/16012374/3abb3a87-74b6-4bb6-8af5-99753996dce5)
_Table from https://github.com/ryanoasis/nerd-fonts/issues/365#issuecomment-1254969225_

And then, if you look closely _Octicons_ is marked as 'not stable'. But we also updated them.
Nerd Fonts set something up to somehow guarantee the codepoint stability as best as possible.
That means only dropped icons will ... be dropped, and their spaces are reused by new icons.
We even kept/modernized one Octo Icon that has been dropped (https://github.com/ryanoasis/nerd-fonts/pull/1215).

> Without other substantial information, the trend looks like years-long cycles.

Yes, I do not expect a weekle MDI update ;-)

2023-05-11 16:38 UTC, Finii commented
> It's unclear there will ever be a v4

That's correct. We accumulated several (breaking) changes over years for `v3` and/but I see no reason to break again.
There is enough un-breaking stuff we can do to keep us entertained the next years :-)

And as I said, upstream might ignore codepoint stability, but _we_ care. Codepoint stability tool [at work](https://github.com/ryanoasis/nerd-fonts/pull/1156#issuecomment-1483859347).

2023-05-11 17:00 UTC, gotgenes commented
@Finii Thank you, that was really informative!

@jesseduffield With this additional information, do you still want to take an approach with a `nerdFontsVersion` today? Or, is this perhaps an approach you want to defer to the next time Nerd Fonts makes a change that Lazygit needs to support before-and-after (should this happen)?

2023-05-12 01:32 UTC, jesseduffield commented
My rationale for letting the user specify the version is less about preparing for future changes (though I would not be surprised if at some point another breaking change in nerd fonts happened), and more about allowing existing lazygit users to upgrade their lazygit version without having to do anything else.

Upgrading nerd fonts is enough of a hassle that I don't want to inflict it on users who upgrade without realising they're about to break their icons. As an example, here's the process I just followed to update my fonts:
* check my preferences in iterm to see which font I was using
* go to https://www.nerdfonts.com
* go to the downloads page
* search for 'DejaVu Sans Mono'
* hit download (file explorer pops up)
* realise I have no idea where my fonts are stored
* google where fonts are stored on mac
* go to that folder
* realise that folder had barely anything in it
* cancel the download
* scroll to bottom where homebrew instructions are
* attempt to download via homebrew, coming up with the name 'font-deja-vu-sans-mono-nerd-font' which seemed sensible
* realise I got it wrong, switch to 'font-dejavu-sans-mono-nerd-font'
* test lazygit, verify the icons now display correctly
* realise I'm using a different font in my vscode terminal given my icons are broken there
* check which font it's using: wtf it's actually the same font?
* restart vscode
* confirm icons work correctly

That took around 10-15 minutes and it wasn't _that_ painful, but it's enough of a task that I want to allow users to defer doing it until they feel like it, without blocking them from updating lazygit.

To be clear here's what lazygit looks like when nerd fonts v2 is still being used (with this PR's code)
![image](https://github.com/jesseduffield/lazygit/assets/8456633/32224fb8-d352-4cb3-8a73-f7fe2bb05256)

So I still want this done in a backwards-compatible way

2023-05-27 04:14 UTC, Saafo commented
At least can we make nerd font v3 users be able to use the new icons, like adding `showIconsV3` option to config.yml

2023-05-30 08:05 UTC, jesseduffield requested changes
Marking as 'changes requested' for my own bookkeeping :)

2023-06-14 15:17 UTC, bmichotte commented
Hello @jesseduffield, do you have any update to share about this ?

Users with a nerd font 3 really have a bad experience with the characters and it will be nice if something was made :)

(btw, how do you have the "tree lines in your commits view" ? Cant' find the options)

2023-06-14 15:47 UTC, stefanhaller commented
> Hello @jesseduffield, do you have any update to share about this ?

This is not waiting for Jesse, he was very clear about how he wants this done. (And for the record, I agree.) This is waiting for someone to make a PR that introduces the option.

> Users with a nerd font 3 really have a bad experience with the characters and it will be nice if something was made :)

This I totally agree with, I'm waiting for this too.

> (btw, how do you have the "tree lines in your commits view" ? Cant' find the options)

```
git:
  log:
    showGraph: always
```

2023-06-14 16:02 UTC, bmichotte commented
> This is not waiting for Jesse, he was very clear about how he wants this done. (And for the record, I agree.) This is waiting for someone to make a PR that introduces the option.
Ok, my bad, I misread the answer

> showGraph: always
Thank you !

2023-06-15 02:40 UTC, gotgenes commented
I don't have the time to add optionality. I'm closing this to make that explicit. Lazygit users who want Nerd Fonts v3 support are welcome to use the patch linked to by this PR.

2023-06-15 02:40 UTC, closed without merging