Fixes and tidying
jesseduffield/lazygit pull request #2711
Opened 2023-06-06 00:11 UTC by amaanq

- **PR Description**

I applied a lot of changes suggested by gopls and staticcheck. The main changes are rearranging struct fields to use less space in memory, reorganizing imports to separate local project imports from others, use _ for unused parameters, and applying DeMorgan's law for cleaner expressions. 

I also tidied up the docs and formatted them as per markdownlint suggestions, as well as the ci scripts.

A lot of these changes **are** subjective, but I hope you'll appreciate them :grin: 

- **Please check if the PR fulfills these requirements**

* [x] Cheatsheets are up-to-date (run `go run scripts/cheatsheet/main.go generate`)
* [x] Code has been formatted (see [here](https://github.com/jesseduffield/lazygit/blob/master/CONTRIBUTING.md#code-formatting))
* [x] Tests have been added/updated (see [here](https://github.com/jesseduffield/lazygit/blob/master/pkg/integration/README.md) for the integration test guide)
* [x] Text is internationalised (see [here](https://github.com/jesseduffield/lazygit/blob/master/CONTRIBUTING.md#internationalisation))
* [x] Docs (specifically `docs/Config.md`) have been updated if necessary
* [x] You've read through your own file changes for silly mistakes etc

2023-06-06 07:16 UTC, jesseduffield commented
I'm glad you're liking Lazygit. In the past I've had bad experiences with PRs that make a bunch of changes using an automated tool, so I'm going to be strict here.

Things I don't want:
* changes to non-go files
* rearranging struct fields
* rearranging imports
* forcing the use of an embedded struct (e.g. 'gitCommon.Common.UserConfig = deps.userConfig' -> 'gitCommon.UserConfig = deps.userConfig')
* replacing unused args with underlines

Things I'm okay with:
* Replace -> ReplaceAll
* if statements to switch statements
* having struct fields each on their own line
* de morgan's law (although I didn't see any examples of this)

As for that changes I'm okay with, I only want to make these changes if the rule can be added to golangci (see `.golangci.yml`). If they can't, there's little point in making the changes because inconsistencies will arise in the future.

Likewise I'd be okay if organising imports could be done upon hitting save (either by gofmt or gofumpt) but I haven't looked into whether that's a thing.

2023-06-06 12:03 UTC, amaanq commented
The organized imports can be done upon save with goimports-reviser, with that knowledge should I keep the organized imports then? I'm not sure if golangci can catch that

2023-06-06 23:07 UTC, jesseduffield commented
Let's keep that out of this PR. We can revisit in another PR

2023-07-10 13:01 UTC, jesseduffield commented
@amaanq do you still intend to get back to this PR? You'll need to rebase onto the latest master as there are conflicts

2023-07-23 06:42 UTC, amaanq commented
yeah, rebased & removed stuff you didn't want in

2023-07-23 11:41 UTC, jesseduffield requested changes
See comments

2023-07-23 11:41 UTC, jesseduffield commented on pkg/commands/git_commands/deps_test.go
> +	gitCommon.UserConfig = deps.userConfig
I don't want any changes related to embedded structs such as this

2023-07-23 11:41 UTC, jesseduffield commented on pkg/gui/context/list_context_trait.go
> -	getDisplayStrings func(startIdx int, length int) [][]string
I don't want any omitted types

2023-07-23 11:41 UTC, jesseduffield commented on pkg/gui/context/working_tree_context.go
> -	getDisplayStrings := func(startIdx int, length int) [][]string {
I don't want this either

2023-07-23 11:41 UTC, jesseduffield commented on pkg/gui/presentation/graph/graph.go
> -		if pipe.kind != STARTS && !(pipe.kind == TERMINATES && pipe.fromPos == commitPos && pipe.toPos == commitPos) {
I find the existing form easier to read

2023-07-23 11:41 UTC, jesseduffield commented on pkg/i18n/dutch.go
> +		IntroPopupMessage:                   "Bedankt voor het gebruik maken van lazygit! 2 dingen die je moet weten:\n\n1) Als je meer van lazygit zijn features wilt leren bekijk dan deze video:\n   https
What has changed here?

2023-09-18 03:31 UTC, jesseduffield commented
Closing

2023-09-18 03:31 UTC, closed without merging