Fix: Update 'zh' to 'zh-CN' in lazygit Language Configuration
jesseduffield/lazygit pull request #2842
Opened 2023-07-29 04:12 UTC by try-to-fly

- **PR Description**
This pull request corrects the language code in lazygit's documentation from 'zh' to 'zh-CN'. The previous 'zh' code was not working properly. This change improves the localization and usability for Chinese users. The change has been validated to ensure the 'zh-CN' option functions as expected.
- **Please check if the PR fulfills these requirements**

* [ ] Cheatsheets are up-to-date (run `go run scripts/cheatsheet/main.go generate`)
* [ ] Code has been formatted (see [here](https://github.com/jesseduffield/lazygit/blob/master/CONTRIBUTING.md#code-formatting))
* [ ] Tests have been added/updated (see [here](https://github.com/jesseduffield/lazygit/blob/master/pkg/integration/README.md) for the integration test guide)
* [ ] Text is internationalised (see [here](https://github.com/jesseduffield/lazygit/blob/master/CONTRIBUTING.md#internationalisation))
* [ ] Docs (specifically `docs/Config.md`) have been updated if necessary
* [ ] You've read through your own file changes for silly mistakes etc

2023-08-06 15:06 UTC, Dragon1573 commented
## Related bug

Unable to launch `lazygit` when setting `gui.language` to `'zh'`. Switching it to `auto` DOES fix the problem and Simplified Chinese is selected as expected.

English `en`, Polish `pl`， Nederlands `nl`, Japanese `ja`, Korean `ko` works as usual.

```shell
23:03:54 ~/.c/lazygit 2ms $ js-yaml config.yml | jq '.gui.language'
"zh"
23:03:58 ~/.c/lazygit 123ms $ lazygit
2023/08/06 23:04:00 Language not found: zh
23:04:00 ~/.c/lazygit 213ms $                                                                                               ✘ 1
```

```shell
23:05:19 ~/.c/lazygit 1ms $ js-yaml config.yml | jq '.gui.language'
"auto"
23:05:22 ~/.c/lazygit 128ms $ lazygit
当前目录不在 git 仓库中。是否在此目录创建一个新的 git 仓库？(y/n): ^C⏎
23:05:28 ~/.c/lazygit 4.45s $                                                                                             ✘ 130
```

2023-08-07 07:11 UTC, Lutra-Fs requested changes
It seems that the language code 'zh-TW' should also be included.

2023-08-07 07:11 UTC, Lutra-Fs commented on docs/Config.md
> +  language: 'auto' # one of 'auto' | 'en' | 'zh-CN' | 'pl' | 'nl' | 'ja' | 'ko' | 'ru'
```suggestion
  language: 'auto' # one of 'auto' | 'en' | 'zh-CN' | 'zh-TW' | 'pl' | 'nl' | 'ja' | 'ko' | 'ru'
```

2023-08-21 07:56 UTC, jesseduffield commented
Thanks for making this

2023-08-21 07:56 UTC, merged