improve `nvim-remote` mode
jesseduffield/lazygit pull request #3508
Opened 2024-04-21 00:50 UTC by cmoog

- If _not_ inside a neovim session, treat as a normal nvim session and suspend lazygit.

- If inside a neovim session:
  - Do not try to suspend lazygit.
  - Send `q` keystroke to neovim session to quit lazygit.
  - Send filename/line/etc. to neovim session.

- **Please check if the PR fulfills these requirements**

* [ ] Cheatsheets are up-to-date (run `go generate ./...`)
* [x] Code has been formatted (see [here](https://github.com/jesseduffield/lazygit/blob/master/CONTRIBUTING.md#code-formatting))
* [ ] Tests have been added/updated (see [here](https://github.com/jesseduffield/lazygit/blob/master/pkg/integration/README.md) for the integration test guide)
* [ ] Text is internationalised (see [here](https://github.com/jesseduffield/lazygit/blob/master/CONTRIBUTING.md#internationalisation))
* [ ] Docs (specifically `docs/Config.md`) have been updated if necessary
* [x] You've read through your own file changes for silly mistakes etc

2024-04-25 00:54 UTC, jesseduffield requested changes
Code looks good, just one comment

2024-04-25 00:54 UTC, jesseduffield commented on pkg/config/editor_presets.go
> +func _const(a bool) func() bool { return (func() bool { return a }) }
Can we rename '_const' to 'returnBool'

2024-05-19 03:55 UTC, jesseduffield commented
I've taken the liberty of squashing the commits into one. Once tests pass we can merge

2024-05-19 04:42 UTC, merged

2024-06-18 13:46 UTC, xzbdmw commented
Are there easy ways to rebind quit in lazygit to a custom command in nvim such as hide terminal?

2024-07-09 17:29 UTC, dudicoco commented
> Are there easy ways to rebind quit in lazygit to a custom command in nvim such as hide terminal?

@cmoog @jesseduffield can you please elaborate on why this PR changes the behavior and quits lazygit instead of suspending it? For me the previous behavior was perfect and this actually feels like a downgrade in experience.

2024-07-09 23:48 UTC, jesseduffield commented
@dudicoco I am regrettably not a neovim daily user so I probably can't do justice to the motivation but my assumption was that if you want to edit random files from the files view, you'd rather switch to the parent neovim process than to create another child one, because by creating another child one, you can end up with many layers of neovim->lazygit->neovim->etc nesting.

Could you elaborate on what specifically you liked about the previous behaviour and what you don't like about the current behaviour?

2024-07-10 08:01 UTC, dudicoco commented
@jesseduffield what you have described is the behavior of `nvim-remote` before this PR as well.
I'm referring specifically to the change in this PR which sends `q` keystroke to neovim session to quit lazygit instead of suspending it.