feat(custom command)!: support multiple contexts within one command
jesseduffield/lazygit pull request #3784
Opened 2024-07-27 17:56 UTC by yam-liu

- **PR Description**

For some custom commands, they can be used in multiple contexts. But for now, if we want to do this, we should copy and paste the same config times and times with just a different **context**. 

Related issue: #3759 

This PR changes the `context` of `customCommand` to `contexts`.

There are at least 3 solutions for this:
**1**: make a **breaking** change to `context` completely.
**2**: keep the `context` and add a new `contexts` key, only one of them can be configured at the same command. `contexts` has a higher priority if both are present.
**3**: keep the `context` key but support both `string` and `array` types.

The current implementation is 1. Maybe 3 is better? Any advice is appreciated.

- **Please check if the PR fulfills these requirements**

* [x] Cheatsheets are up-to-date (run `go generate ./...`)
* [x] Code has been formatted (see [here](https://github.com/jesseduffield/lazygit/blob/master/CONTRIBUTING.md#code-formatting))
* [x] Tests have been added/updated (see [here](https://github.com/jesseduffield/lazygit/blob/master/pkg/integration/README.md) for the integration test guide)
* [x] Text is internationalised (see [here](https://github.com/jesseduffield/lazygit/blob/master/CONTRIBUTING.md#internationalisation))
* [ ] Docs have been updated if necessary
* [x] You've read through your own file changes for silly mistakes etc

2024-07-27 19:34 UTC, stefanhaller commented
Nice, thanks for working on this. 

A fourth solution could be to keep the config as a string, and simply support a comma-separated list of contexts, e.g.
```yaml
  - key: X
    context: commits,branches
```

I think I would be in favor of this, I find this pretty intuitive, it's simple to implement, and it's not a breaking change.

2024-07-28 09:46 UTC, yam-liu commented
@stefanhaller Great advice, I have done the modification. Docs will be updated later.

2024-07-30 10:01 UTC, stefanhaller requested changes
Great work, we're almost there. There's one bug and a minor style thing, see below.

Apart from that, it would be great if we could add an integration test for the case where there's more than one context (in addition to a test for "global" as suggested below). It should be easy to do given the existing examples that we already have.

2024-08-01 13:27 UTC, stefanhaller commented
Very nice, good work on the tests. Just one small suggestion for one of the tests below.

Now the only complaint I have left is the commit history. My suggestion for structuring the commits would be:
- a commit that adds the test for the global context
- all the other changes (the implementation, the other test, and the docs) as a single, second commit.

Also, I find your use of "feat" in the commit messages questionable. I'm not a fan of conventional commits myself, I'd rather omit that entirely, but if you do want to use it, please do it consistently. A commit that adds a test shouldn't be labelled with "feat".

2024-08-02 09:57 UTC, stefanhaller approved these changes
Nice, thanks. I took the liberty of making the remaining commit history changes that I suggested myself.

2024-08-02 09:59 UTC, merged