WIP: collapse/uncollapse all files in tree
jesseduffield/lazygit pull request #4131
Opened 2024-12-27 21:03 UTC by mtrajano

Seems like this feature is highly requested #4095 #3554

Did a quick wip pr. I got the core functionality working with files and had some questions on what can be improved in order to polish it more. I.e. What keymaps if any to add to these, should the functionality be to toggle vs collapse and uncollapse separately, and if this should be added anywhere else (right now it's just for the file tree)
Another improvement is that it now 

Once I figure this out I can add the tests, documentations and anything else that's missing. I'm also pretty new to the language so if there's a way I can structure this better please let me know

Example of functionality working:
![example](https://github.com/user-attachments/assets/bb480b77-dace-4c5a-90b5-27daddf19eba)

2024-12-29 17:54 UTC, stefanhaller commented
> What keymaps if any to add to these

I could imagine `-` for collapsing, and `=` for expanding. At least they are easy to reach on a US keyboard layout. Anybody got any better ideas?

> should the functionality be to toggle vs collapse and uncollapse separately

I would probably do separate ones. For toggling it wouldn't be quite clear what the exact logic would be.

> and if this should be added anywhere else (right now it's just for the file tree)

Yes, in `commits_files_controller.go`; this handles the list of files that you see when pressing enter on a commit. I'm not aware of any other places besides these two.

2025-01-02 03:50 UTC, jesseduffield commented
> I could imagine - for collapsing, and = for expanding.

That sounds good to me

2025-01-10 19:20 UTC, mtrajano commented
@jesseduffield @stefanhaller This pr is ready as well with localization and an integration test. I noticed there is a plan to add generics to generalize the logic between commit files and the files view but it does not look trivial. I can give it a shot in a separate pr although I might have some questions.

2025-01-11 02:39 UTC, jesseduffield requested changes
Just one comment, otherwise LGTM. Tested it out and it works great

2025-01-11 02:39 UTC, jesseduffield commented on pkg/i18n/english.go
> +		CollapseAllTooltip:                   "Collapse all entries in the files tree",
```suggestion
		CollapseAllTooltip:                   "Collapse all directories in the files tree",
```
Likewise with below

2025-01-11 02:40 UTC, jesseduffield commented
> I noticed there is a plan to add generics to generalize the logic between commit files and the files view but it does not look trivial. I can give it a shot in a separate pr although I might have some questions.

That would be great! Happy to answer any questions you have

2025-01-12 13:45 UTC, stefanhaller commented
I tested this and it works nicely, but what I'm missing is to keep the selection (if possible). This won't always be possible, e.g. when collapsing it will only be possible if a top-level entry is selected, and I'd be ok with the selection jumping to an arbitrary top-level entry when that's not the case (although it would be nice if it would jump to the top-level entry which is a parent of what's currently selected; this doesn't seem super important though). When expanding, however, it should always be possible, and it's a bit annoying that it isn't right now.

2025-01-12 17:29 UTC, stefanhaller commented
Ok, I had a bit of a closer look at the code and found a few more things that can be improved. I pushed two commits, please see their commit messages for details.

2025-01-12 20:51 UTC, jesseduffield reviewed
Those changes look good to me @stefanhaller

2025-01-13 20:11 UTC, stefanhaller commented on pkg/i18n/english.go
> +		CollapseAllTooltip:                   "Collapse all entries in the files tree",
Fixed in d5374accdaac.

2025-01-13 20:12 UTC, stefanhaller commented
I added one more commit (b04d1f5a281b) that renames some UncollapseAll methods to ExpandAll, since that seems to be the terminology we're using for this.

I'm gonna squash this now, this is ready to merge from my side.

2025-01-13 20:18 UTC, merged

2025-10-22 12:10 UTC, halo commented
Right now one can toggle one folder at a time, or all folders (which was implemented here). I was wondering if toggling a subtree would not be a useful feature (I find myself doing that a lot and it's standard in tree views on macOS).

Since I never wrote anything in go, I spent a few hours asking AI to help me out implementing this feature and this is the result: https://github.com/halo/lazygit/pull/2 and it works nicely when I try it out manually.

I'm not familiar with how the lazygit code base is being organized such that it doesn't become messier over time. There is surely some duplication now with this feature here (because toggling a subtree is very similar to toggling all folders). And skimming through the code base there immediately sprang to mind a few unrelated places where things could be DRYer (such as `FileTree` versus `CommitFileTree`) but I don't want to bloat the commit even more. 

If you don't mind @stefanhaller, I'd love to have a human look at the changes and tell me whether I'm on the right track and if this has a chance of being merged with some modifications. If so, I'll gladly create a PR so that someone can review it.

(The tests are okay-ish for a first shot by AI, but not perfect. And I'm not dogmatic about Alt+Enter, I just took that key combination because that's default in macOS.)

Thank you for your time.